In [8]:
from tensorflow.keras.models import load_model
model = load_model('mnistCNN.h5')
from PIL import Image
import numpy as np
for index in range(4):
  img=Image.open('Downloads/data/'+str(index)+'.png').convert("L")
  img=img.resize((28,28))
  im2arr=np.array(img)
  im2arr=im2arr.reshape(1,28,28,1)
  #prediction
  y_pred=model.predict(im2arr)
  y_pred=np.round(y_pred)
  print(y_pred) 

1/1 [==============================] - 0s 157ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 47ms/step
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
1/1 [==============================] - 0s 40ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
1/1 [==============================] - 0s 40ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
